### ISSUE TITLE
Image src with relative path in site preview

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#96] opened 2020-12-18 15:56 UTC
**Describe the bug**
The site preview hosted at https://preview.seshrs.ml/previews/ seems to rewrite relative img src paths as absolution paths.  Here's an example:

**To Reproduce**

1. Make a subdirectory, e.g. `/docs/w21/`
2. Add an image `/docs/w21/img/logo.png`
3. Add HTML image with a relative src to `/docs/w21/index.html`, e.g. `<img src="img/logo.png">`
4. Create PR
5. View the site preview
6. Observe 404 in the console in response to a `GET` request to the *wrong* path, e.g., `https://preview.seshrs.ml/previews/eecs280staff/eecs280.org/168/img/logo.png`

**Expected behavior**
Actual path: `https://preview.seshrs.ml/previews/eecs280staff/eecs280.org/<PR>/img/logo.png`

Expected path: `https://preview.seshrs.ml/previews/eecs280staff/eecs280.org/<PR>/w21/img/logo.png`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version 83

**Additional context**
Local preview via `bundle exec jekyll serve` works as expected.

**Comment by seshrs** [comment] 2020-12-19 16:44
Thanks for reporting @awdeorio! Haha, the trailing slash issues always come back to haunt me 😆 

So the issue is that when you visit the `/w21` subdirectory, the URL *should* be rewritten to include a trailing slash. That way, browsers will correctly expand relative image paths in the HTML. GitHub Pages does this correctly, it redirects `https://eecs280staff.github.io/eecs280.org/w21` to `https://eecs280staff.github.io/eecs280.org/w21/` (notice the trailing slash). However, Primer Spec Preview does not, because [Sinatra](http://sinatrarb.com/)'s static file routing does not.

I think the best way to fix this is to add custom routing for the preview directory instead of relying on Sinatra's static file-serving logic. I'll look into implementing this over the weekend.

---

PS: I'm going to move this issue to the Primer Spec Preview repo. I initially built it for Primer Spec, but I figured that it was useful enough to exist on its own.

**Comment by seshrs** [comment] 2020-12-20 05:30
I've fixed the issue, and the fix has been deployed. You should be able to validate the fix on the PR previews right away! :)

**Closed by seshrs** 2020-12-20 05:30 UTC
Labels: bug
